#include <stdio.h>
#include "main.h"

/**
 * write_line  - prints the new lines generated by the other func
 * Return: Print stdout the new_lines
 */ 

void write_line(char *new_line)
{
	printf("%s\n", new_line);
}
